<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <OutputPath>..\..\artifacts\bin\$(MSBuildProjectName)\$(Configuration)\</OutputPath>
    <TargetFrameworks>netcoreapp2.1</TargetFrameworks>
    <Configuration>$(Configuration)</Configuration>

    <RootNamespace>Atlas.Provider.Core</RootNamespace>
    <Description>Entity Framework Core Command-line Tools</Description>
    <Nullable>enable</Nullable>
    <IncludeSource>false</IncludeSource>
    <LangVersion>latest</LangVersion>
    <RollForward>Major</RollForward>

    <IsPackable>false</IsPackable>
    <CheckEolTargetFramework>False</CheckEolTargetFramework>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="3.11.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.Workspaces.MSBuild" Version="3.11.0" />
    <PackageReference Include="Microsoft.Build.Locator" Version="1.4.1" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="3.11.0" />
  </ItemGroup>
</Project>