-- Create "Blogs" table
CREATE TABLE "public"."Blogs" (
  "BlogId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "Url" character varying(200) NOT NULL,
  "Rating" numeric(5,2) NOT NULL,
  "Title" text NOT NULL,
  "Content" text NOT NULL,
  "Author" character varying(200) NOT NULL DEFAULT 'Anonymous',
  PRIMARY KEY ("BlogId"),
  CONSTRAINT "AK_Blogs_Url" UNIQUE ("Url")
);
-- Create "Post" table
CREATE TABLE "public"."Post" (
  "PostId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "Title" text NOT NULL,
  "Content" text NOT NULL,
  "BlogUrl" character varying(200) NULL,
  PRIMARY KEY ("PostId"),
  CONSTRAINT "FK_Post_Blogs_BlogUrl" FOREIGN KEY ("BlogUrl") REFERENCES "public"."Blogs" ("Url") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create index "IX_Post_BlogUrl" to table: "Post"
CREATE INDEX "IX_Post_BlogUrl" ON "public"."Post" ("BlogUrl");
