-- Add new schema named "Blogging"
CREATE SCHEMA "Blogging";
-- Create "AuditEntry" table
CREATE TABLE "public"."AuditEntry" (
  "Name" text NULL
);
-- Create "Blogs" table
CREATE TABLE "Blogging"."Blogs" (
  "BlogId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "Url" character varying(200) NOT NULL,
  "Rating" numeric(5,2) NOT NULL,
  "Title" text NOT NULL,
  "Content" text NOT NULL,
  "Author" character varying(200) NOT NULL DEFAULT 'Anonymous',
  CONSTRAINT "PK_Blogs" PRIMARY KEY ("BlogId"),
  CONSTRAINT "AK_Blogs_Url" UNIQUE ("Url")
);
-- Set comment to column: "Content" on table: "Blogs"
COMMENT ON COLUMN "Blogging"."Blogs"."Content" IS 'Content contains new lines \n\r and 
 for example';
-- Create "Posts" table
CREATE TABLE "public"."Posts" (
  "PostId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "Title" text NOT NULL,
  "Content" text NOT NULL,
  "BlogUrl" character varying(200) NULL,
  CONSTRAINT "PK_Posts" PRIMARY KEY ("PostId"),
  CONSTRAINT "FK_Posts_Blogs_BlogUrl" FOREIGN KEY ("BlogUrl") REFERENCES "Blogging"."Blogs" ("Url") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create index "IX_Posts_BlogUrl" to table: "Posts"
CREATE INDEX "IX_Posts_BlogUrl" ON "public"."Posts" ("BlogUrl");
